name: Build PJ

on: 
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true  # Ensure submodules are checked out
      - name: Set up Godot templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates
        if [ -d "/root/.local/share/godot/templates/" ]; then
          cp -r /root/.local/share/godot/templates/* ~/.local/share/godot/export_templates/
        else
          echo "Godot templates directory does not exist. Please ensure the templates are available."
          exit 1
        fi
      - name: Clean up Git configurations
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive git config --global --unset-all http.https://github.com/.extraheader || true
      - name: Build Godot
        id: build
        uses: yeslayla/build-godot-action@v1.5.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
