name: Build PJ

on: 
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true  # Ensure submodules are checked out

      - name: Export Godot Project
        uses: firebelley/godot-export@v5
        with:
          version: 4.3
          preset: ${{ matrix.platform }}
          export_debug: true
          cache: true
          archive_output: false  # Set to true if you want a ZIP file

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: build/${{ matrix.platform }}/*
