name: Build PJ

on: 
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true  # Ensure submodules are checked out
      - name: Clean up Git configurations
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive git config --global --unset-all http.https://github.com/.extraheader || true
      - name: Install Godot Export Templates
        run: |
          mkdir -p ~/godot/export_templates
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz -O /tmp/templates.tpz
          unzip /tmp/templates.tpz -d ~/godot/export_templates
      - name: Build Godot
        id: build
        uses: yeslayla/build-godot-action@v1.5.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
